### PR TITLE
[WIP] Fix unscaled stroke with gradient

### PR DESCRIPTION
**Pull request by MaxGraey**
Fix some issues produce gradient strokes with unscaled attribute.

- [x] Fix width
- [x] Fix movement
- [x] Fix scale
- [x] Fix dashes
- [ ] Fix tests

Plz don't merge this PR yet.

### CODE REVIEW

**Comment by MaxGraey** [comment]
Currently test fail because Phantom not support [this feature](https://developer.mozilla.org/ru/docs/Web/API/CanvasRenderingContext2D/currentTransform). But all works as expected. So I thinking of how to resolve this.

**Comment by lavrton** [comment]
Hmmm. We need to find a workaround. `currentTransform` has a very poor browser's support.

**Comment by MaxGraey** [comment]
I see only one solution: store (serialize) last transform manually, but this need refactoring in many places

**Comment by MaxGraey** [comment]
@lavrton Did you know how resolve this without `currentTransform`? Is it possible have own `transform` variable? Or use `this.getAbsoluteTransform().getMatrix()`?

**Comment by lavrton** [comment]
I think we can try to use absolute transform for that case.

But I am not sure about consistent behavior when `scaleX !== scaleY`.

**Comment by lavrton** [comment]
There was a full rewrite of Konva codebase so it is very hard to review and merge the pull request now.
And also I don't really remember what does it fix. So I have to close it for now.

But anyway I am happy to discuss it again and see if we can merge it.

**Pull request closed without merging**
