### PR TITLE
global document mock

### PR DESCRIPTION
**Pull request by tomasziwaszko**
There was an error while stage deserialization - document was undefined

### CODE REVIEW

**Comment by lavrton** [comment]
Hmmm. It is better not to touch `global` variable. Can you show a demo a code sample where you see the error?

**Comment by tomasziwaszko** [comment]
`Konva.Node.create(jsonData, 'container');` There is an other way to deserialize stage on Node.js side?

**Comment by lavrton** [comment]
Just create a node without a container `Konva.Node.create(jsonData);`. Works good for me.

**Comment by tomasziwaszko** [comment]
Works good for me too. Thx

**Pull request closed without merging**
