### PR TITLE
Added kerning support (issue #334)

### PR DESCRIPTION
**Pull request by EugeneSqr**
Please see the updated [jsfiddle](https://jsfiddle.net/3ct0e6sd/3/).

This time letter spacing should be the same for all browsers (even if they don't have native support for kerning):

chrome

ie11

### CODE REVIEW

**Comment by lavrton** [comment]
I think we may need it for both `Konva.Text` and `Konva.TextPath`.
Also, it will be really good to have docs (jsdoc) and unit tests.

@EugeneSqr Do you want to make such updates?

**Comment by EugeneSqr** [comment]
I can handle the docs and unit tests, however I believe we should keep Konva.Text unchanged.

Konva.TextPath calculates each letter position "by hand", therefore it's too slow, when it comes to dragging or moving a lot of text. At this point we can use Konva.Text for "heavy" but "forgiving" scenarios and keep Konva.TextPath for pixel perfect but slow things.

**Comment by EugeneSqr** [comment]
@lavrton it's done

**Comment by lavrton** [comment]
Thanks!

**Pull request merged**
