### PR TITLE
Add preventDefault option to NodeConfig (type definition) + Add Konva.Text.ellipsis

### PR DESCRIPTION
**Pull request by hbroer**
This config option is important to overwrite the default behaviour. 

Example:
<Rect {...props} preventDefault={false} />

### CODE REVIEW

**Comment by hbroer** [comment]
meanwhile i added text ellipsis.
if Konva.Text config is set to wrap='none' and ellipsis=true, then it will add ... to the string.

**Comment by lavrton** [comment]
There must be separate PR.

And I don't get why `ellipses` is useful. Isn't it simpler to cut string manually?

**Comment by hbroer** [comment]
Then i need to figure out how to split it. I will do.

The Konva.Text Element does automatically cut strings if they can't fit into the frame. That is good. But without that ellipsis option u can't define that it should make that visible for the user. Doing that outside of where the cutting happens would make it much more complicated.

CSS has a option for this too: "text-overflow: ellipsis"

**Comment by lavrton** [comment]
Please, make an another Rull Request.

Also `preventDefault` should be part of `ShapeConfig` (not `Node`).

BTW, thanks for the contribution.

**Comment by hbroer** [comment]
This can be canceled. I splitted it up.

**Pull request closed without merging**
