### PR TITLE
Do not stop dragging

### PR DESCRIPTION
**Pull request by myzonjkee**
Hi, 
I have prepared an [example](https://codesandbox.io/s/konva-drag-example-lfq3r) where you can reproduce my issue. Try to drag down a first rectangle and check your console.

In your console you may see something like this:

DevTools_-_codesandbox_io_s_tender-lehmann-lfq3r

Important part of a call stack I have emphasised by yellow color.
After call "insertBefore" it calls "Node.remove" where dragging will be braked...

### CODE REVIEW

**Comment by lavrton** [comment]
I can't reproduce. I don't see any errors. And we should stop dragging if a node is going to be removed.

**Comment by myzonjkee** [comment]
Yep. 
Thank you for your reply)

**Comment by lavrton** [comment]
But I am still interested to know how did you have that error. If you can reproduce it, please add more info.

**Comment by myzonjkee** [comment]
The [example](https://codesandbox.io/s/konva-drag-example-lfq3r) I have created to reproduce the issue just works fine for me...

ezgif com-resize

**Comment by lavrton** [comment]
That was a bug in `react-konva` fixed with the last version.
Check it: https://codesandbox.io/s/konva-drag-example-01ulf

**Comment by lavrton** [comment]
Thanks for the report! It was very helpful.

**Comment by myzonjkee** [comment]
Thank you!

**Pull request closed without merging**
