### PR TITLE
add option to pass fn as a selector in find method instead of a string.

### PR DESCRIPTION
**Pull request by seethroughtrees**
While using the library, I found myself wanting to find by more than just selectors, so I added a .findWhere() method.

This allows you to pass a function into a find method instead of a selector.
I know we could modify the .find method, but it felt like too many changes to be worth it.

Please let me know if this is worth adding, and if any changes need to be made.

### CODE REVIEW

**Comment by lavrton** [comment]
Yeah. I think it is a useful method. But I think it will be better to overload `find` method. So it can work like this:

```js
group.find('Shape');
group.find(function(child) {
   // child here can be a direct child or child of a child
});

**Comment by seethroughtrees** [comment]
sure.  I can do that instead.

Just to confirm, overloading `find` will require some changes inside the method as its pretty much written to handle only strings.  We'll have to modify `isValidSelector` (which is used by `_isMatch`) and clean up some of the logic depending on the argument type.  

that okay to modify?

**Comment by seethroughtrees** [comment]
per your initial request, I updated the PR to overload the find method.  It should now take string selectors, or a function filter.

**Comment by lavrton** [comment]
Looks good to me. Thanks!

**Pull request merged**
