### PR TITLE
feat: :sparkles: The Image adds rounded corner support

### PR DESCRIPTION
**Pull request by iaosee**
The image supports setting rounded corners, which is very useful in my project.

image

### CODE REVIEW

**Comment by lavrton** [comment]
That is a good Pull Request. Most of the tests were disabled in the repo. I just restored them back and some image tests are failing now. Can you please review them and restore?

Try to make sure that old image tests are working the same way.

**Comment by iaosee** [comment]
Ok, let me check it.

**Comment by iaosee** [comment]
The Image test is now restored, but I don't know why the other tests fail.

image

**Comment by lavrton** [comment]
Released in `8.4.0`

**Pull request merged**
